### ISSUE TITLE
Feature Request - Message ID 14 and 15

### ISSUE THREAD

**Issue by alxscott** [arthurrump/esphome-opentherm#29]
Hi,

Firstly thanks for your hard work; but this is really helping optimise my heating.

Unfortunately I have an issue with my boiler Short Cycling. I'm pretty sure it's due to the boiler now being oversized having shifted to full UFH.

That said, reading Opentherm Specification v2.2 Section 5.3.8.2 Boiler Sequencer Control - I think message IDs 14 and 15 would be really useful ( at least for me!). They are included in Ihors library as MaxRelModLevelSetting and MaxCapacityMinModLevel respectively.

Would this be possible to be added to your component? Or is it as simple as copy / paste / modify a suitable section of schema.py?

Thanks!

**Comment by hannahdiels** [comment]
Hi, this repo seems unmaintained. I believe what you are looking for is included in https://github.com/FreeBear-nc/esphome-opentherm and it has merged pull requests recently, so it's maintained.

**Comment by alxscott** [comment]
That’s awesome; thank you!
